1756041148584	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1756042431539	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1756042431540	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1756042431541	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1756042431550	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1756042431554	Sync.SyncScheduler	DEBUG	Woke from sleep.
1756042431554	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1756042431554	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1756042431554	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1756042433556	Sync.Service	DEBUG	User-Agent: Firefox/142.0 (Linux x86_64) FxSync/1.144.0.20250818081258.desktop
1756042433556	Sync.Service	INFO	Starting sync at 2025-08-24 15:33:53 in browser session MWcCp-DVR1gr
1756042433556	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1756042433557	Sync.Status	INFO	Resetting Status.
1756042433557	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1756042433557	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1756042433557	FirefoxAccounts	DEBUG	getOAuthToken enter
1756042433557	FirefoxAccounts	TRACE	getCachedToken returning cached token
1756042433557	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1756042433558	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1756042433559	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1756042433559	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1756042433559	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/197106278/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1756042433559	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1756042433559	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1756042433559	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1756042433559	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1756042433561	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
